Add autolabel functionality to backend
nots-2022-g1/nots-agls pull request #51
Opened 2022-04-03 16:18 UTC by YVbakker

Deze PR voegt de volgende functionaliteit toe:

+ de3bb5db67488d1996dba4c04899bca334dff62a Add AutoLabelConfig entity
+ 356e57da786e40dcbd594e10d9df0a2fec95a5da Add IEnumerable of LabeledData Add, minor refactor
+ a751affe3150b1622471f5616c61d4ad3ce9b0cf Add autolabel endpoint and basic algorithm

TODO mogelijk in frontend inbouwen om dit aan te roepen, op een logische plaats

closes #42

2022-04-05 07:12 UTC, ThijmenMaus requested changes
Ziet er goed uit, code-formatting feedback

2022-04-05 07:12 UTC, ThijmenMaus commented on api/Controllers/DataSetsController.cs
> +    public DataSetsController(IGenericCrudService<Dataset> service, ILabeledDataService labeledDataService,
```csharp
public DataSetsController(
    IGenericCrudService<Dataset> service,
    ILabeledDataService labeledDataService,
    IGitCommitService gitCommitService,
    IKeywordService keywordService
) : base(service) {
  // ...
}
```

2022-04-06 07:53 UTC, ThijmenMaus approved these changes

2022-04-06 07:53 UTC, ilivss approved these changes

2022-04-06 12:02 UTC, merged